//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace HeadacheCDSSWeb.Models
{
    public partial class DocSuggestionSet
    {
        public int Id { get; set; }
        public string Suggestion { get; set; }
        public Nullable<System.DateTime> SuggestionTime { get; set; }
        public Nullable<int> IfNew { get; set; }
        public string PatBasicInforId { get; set; }
    
        public virtual PatBasicInfor PatBasicInforSet { get; set; }
    }
    
}
