//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace HeadacheCDSSWeb.Models
{
    public partial class DoctorAccount
    {
        public DoctorAccount()
        {
            this.PatBasicInfor = new HashSet<PatBasicInfor>();
        }
    
        public int Id { get; set; }
        public string UserName { get; set; }
        public string PassWord { get; set; }
        public string Hospital { get; set; }
        public string ChiefDoctor { get; set; }
        public int RegionalCenterAccountID { get; set; }
    
        public virtual ICollection<PatBasicInfor> PatBasicInfor { get; set; }
        public virtual RegionalCenterAccount RegionalCenterAccount { get; set; }
    }
    
}
