//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace HeadacheCDSSWeb.Models
{
    public partial class HeadachePlace
    {
        public int Id { get; set; }
        public string Position { get; set; }
        public string SpecificPlace { get; set; }
        public int HeadachaOverViewId { get; set; }
    
        public virtual PrimaryHeadacheOverView HeadachaOverView { get; set; }
    }
    
}
