//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace HeadacheCDSSWeb.Models
{
    public partial class HeadacheDiary
    {
        public int Id { get; set; }
        public System.DateTime RecordTime { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public string PatBasicInforId { get; set; }
        public Nullable<int> Degree { get; set; }
        public Nullable<int> Position { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> IfAroundEye { get; set; }
        public Nullable<int> Type { get; set; }
        public string TypeComment { get; set; }
        public Nullable<int> IfActivityAggravate { get; set; }
        public string Prodrome { get; set; }
        public string Companion { get; set; }
        public string Precipiating { get; set; }
        public string PrecipiatingComment { get; set; }
        public string Mitigating { get; set; }
        public string DrugList { get; set; }
        public Nullable<int> AidDiagnosis { get; set; }
        public string MitigatingComment { get; set; }
    
        public virtual PatBasicInfor PatBasicInfor { get; set; }
    }
    
}
