//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace HeadacheCDSSWeb.Models
{
    public partial class Lifestyle
    {
        public int Id { get; set; }
        public Nullable<bool> SmokeState { get; set; }
        public string SmokeYear { get; set; }
        public Nullable<bool> DrinkState { get; set; }
        public string DrinkYear { get; set; }
        public string TeaPerDay { get; set; }
        public string CoffePerDay { get; set; }
        public Nullable<bool> ExerciseOften { get; set; }
    
        public virtual PatBasicInfor PatBasicInfor { get; set; }
    }
    
}
