//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace HeadacheCDSSWeb.Models
{
    public partial class PatinfoForRe
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Sex { get; set; }
        public string Age { get; set; }
        public string HeadacheStyle { get; set; }
        public string Data { get; set; }
        public string PatBasicInforId { get; set; }
        public string ListID { get; set; }
    
        public virtual PatBasicInfor PatBasicInfor { get; set; }
    }
    
}
