//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace HeadacheCDSSWeb.Models
{
    public partial class PreviousDrug
    {
        public int Id { get; set; }
        public string DrugCategory { get; set; }
        public string DrugName { get; set; }
        public string DayAmoutnPerM { get; set; }
        public string MonthTotalAmount { get; set; }
        public string PatBasicInforId { get; set; }
        public string DrugApplication { get; set; }
        public string PatBasicInforId1 { get; set; }
    
        public virtual PatBasicInfor PatBasicInfor { get; set; }
    }
    
}
