//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace HeadacheCDSSWeb.Models
{
    public partial class PrimaryHeadacheOverView
    {
        public PrimaryHeadacheOverView()
        {
            this.HeadachePlace = new HashSet<HeadachePlace>();
            this.HeadacheAccompany = new HashSet<HeadacheAccompany>();
            this.HeadacheProdrome = new HashSet<HeadacheProdrome>();
            this.MitigatingFactors = new HashSet<MitigatingFactors>();
            this.PrecipitatingFactor = new HashSet<PrecipitatingFactor>();
            this.PremonitorySymptom = new HashSet<PremonitorySymptom>();
        }
    
        public int Id { get; set; }
        public string HeadacheType { get; set; }
        public string HeadacheDegree { get; set; }
        public string HeadcheTime { get; set; }
        public string HeacheTimeUnit { get; set; }
        public string FrequencyPerMonth { get; set; }
        public string OnsetFixedPeriod { get; set; }
        public System.DateTime OnsetDate { get; set; }
        public string OnsetAmount { get; set; }
        public string DailyAggravation { get; set; }
        public string FirstOnsetContinue { get; set; }
    
        public virtual ICollection<HeadachePlace> HeadachePlace { get; set; }
        public virtual ICollection<HeadacheAccompany> HeadacheAccompany { get; set; }
        public virtual ICollection<HeadacheProdrome> HeadacheProdrome { get; set; }
        public virtual ICollection<MitigatingFactors> MitigatingFactors { get; set; }
        public virtual ICollection<PrecipitatingFactor> PrecipitatingFactor { get; set; }
        public virtual VisitRecord VisitRecord { get; set; }
        public virtual ICollection<PremonitorySymptom> PremonitorySymptom { get; set; }
    }
    
}
