//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace HeadacheCDSSWeb.Models
{
    public partial class RegionalCenterAccount
    {
        public RegionalCenterAccount()
        {
            this.DoctorAccount = new HashSet<DoctorAccount>();
        }
    
        public int ID { get; set; }
        public string UserName { get; set; }
        public string PassWord { get; set; }
        public string Region { get; set; }
        public int NationalCenterAccountID { get; set; }
    
        public virtual NationalCenterAccount NationalCenterAccount { get; set; }
        public virtual ICollection<DoctorAccount> DoctorAccount { get; set; }
    }
    
}
