//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace HeadacheCDSSWeb.Models
{
    public partial class SleepStatus
    {
        public int Id { get; set; }
        public string TimePerDay { get; set; }
        public string DifficultFallingAsleep { get; set; }
        public string Dreaminess { get; set; }
        public string FestlessSleep { get; set; }
        public string SleepyDayTime { get; set; }
    
        public virtual VisitRecord VisitRecord { get; set; }
    }
    
}
